### ISSUE TITLE
Add clean gitlab registry without project ID

### ISSUE THREAD

**Issue by DmitriyMurzin** [ukfast/gitlab-registry-cleanup#1]
Hello, for such a functionality, you can write a bash script in 4 lines using curl, please add automatic receipt of project ID, this will be a very useful functionality, it would also be cool to enable regular expressions for project names (image name).
Thanks for your hard work)

**Comment by 0x4c6565** [comment]
Hi @DmitriyMurzin - I've added a PR (#3) which allows for omitting of project ID, and allows for option group ID filtering. I've also changed image to be optional.

**Comment by 0x4c6565** [comment]
> Hi @DmitriyMurzin - I've added a PR (#3) which allows for omitting of project ID, and allows for option group ID filtering. I've also changed image to be optional.

This has been merged and released in v0.1.0
